export default {
  term: "new york",
  moresuggestions: 25,
  autoSuggestInstance: null,
  trackingID: "6122345b714021dc2e8c515673a3edf5",
  misspellingfallback: false,
  suggestions: [
    {
      group: "CITY_GROUP",
      entities: [
        {
          geoId: "2621",
          destinationId: "1506246",
          landmarkCityDestinationId: null,
          type: "CITY",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.75668,
          longitude: -73.98647,
          searchDetail: null,
          caption:
            "<span class='highlighted'>New</span> <span class='highlighted'>York</span>, New York, United States of America",
          name: "New York",
        },
        {
          geoId: "129440",
          destinationId: "1535616",
          landmarkCityDestinationId: null,
          type: "NEIGHBORHOOD",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.77827894430704,
          longitude: -73.96990559824117,
          searchDetail: null,
          caption:
            "Manhattan, <span class='highlighted'>New</span> <span class='highlighted'>York</span>, New York, United States of America",
          name: "Manhattan",
        },
        {
          geoId: "183700",
          destinationId: "1409641",
          landmarkCityDestinationId: null,
          type: "CITY",
          redirectPage: "DEFAULT_PAGE",
          latitude: 41.156723296590606,
          longitude: -73.99378341652913,
          searchDetail: null,
          caption:
            "<span class='highlighted'>New</span> City, New <span class='highlighted'>York</span>, United States of America",
          name: "New City",
        },
        {
          geoId: "6234083",
          destinationId: "11108016",
          landmarkCityDestinationId: null,
          type: "REGION",
          redirectPage: "DEFAULT_PAGE",
          latitude: 43.04737748563339,
          longitude: -75.65465713202158,
          searchDetail: null,
          caption:
            "Upstate <span class='highlighted'>New</span> <span class='highlighted'>York</span>, New York, United States of America",
          name: "Upstate New York",
        },
        {
          geoId: "6056124",
          destinationId: "1643095",
          landmarkCityDestinationId: null,
          type: "CITY",
          redirectPage: "DEFAULT_PAGE",
          latitude: 42.439552,
          longitude: -76.497787,
          searchDetail: null,
          caption:
            "Ithaca (and vicinity), <span class='highlighted'>New</span> <span class='highlighted'>York</span>, United States of America",
          name: "Ithaca (and vicinity)",
        },
        {
          geoId: "9775",
          destinationId: "1643110",
          landmarkCityDestinationId: null,
          type: "CITY",
          redirectPage: "DEFAULT_PAGE",
          latitude: 43.081409,
          longitude: -73.785431,
          searchDetail: null,
          caption:
            "Saratoga Springs, <span class='highlighted'>New</span> <span class='highlighted'>York</span>, United States of America",
          name: "Saratoga Springs",
        },
        {
          geoId: "149004",
          destinationId: "1633594",
          landmarkCityDestinationId: null,
          type: "NEIGHBORHOOD",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.71025273032951,
          longitude: -73.81875841072811,
          searchDetail: null,
          caption:
            "Queens, <span class='highlighted'>New</span> <span class='highlighted'>York</span>, United States of America",
          name: "Queens",
        },
        {
          geoId: "6487",
          destinationId: "1633573",
          landmarkCityDestinationId: null,
          type: "CITY",
          redirectPage: "DEFAULT_PAGE",
          latitude: 42.71463622576411,
          longitude: -74.90439720766221,
          searchDetail: null,
          caption:
            "Cooperstown, <span class='highlighted'>New</span> <span class='highlighted'>York</span>, United States of America",
          name: "Cooperstown",
        },
      ],
    },
    {
      group: "HOTEL_GROUP",
      entities: [
        {
          geoId: "19768",
          destinationId: "112922",
          landmarkCityDestinationId: null,
          type: "HOTEL",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.76225,
          longitude: -73.97874,
          searchDetail: null,
          caption:
            "<span class='highlighted'>New</span> <span class='highlighted'>York</span> Hilton Midtown, New York, New York, United States of America",
          name: "New York Hilton Midtown",
        },
      ],
    },
    {
      group: "LANDMARK_GROUP",
      entities: [
        {
          geoId: "502080",
          destinationId: "1409835",
          landmarkCityDestinationId: "1506246",
          type: "LANDMARK",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.757410161691084,
          longitude: -73.98618346732785,
          searchDetail: null,
          caption:
            "Times Square, <span class='highlighted'>New</span> <span class='highlighted'>York</span>, New York, United States of America",
          name: "Times Square",
        },
        {
          geoId: "6142027",
          destinationId: "1635518",
          landmarkCityDestinationId: "1506246",
          type: "LANDMARK",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.768058,
          longitude: -73.981893,
          searchDetail: null,
          caption:
            "Columbus Circle, <span class='highlighted'>New</span> <span class='highlighted'>York</span>, New York, United States of America",
          name: "Columbus Circle",
        },
        {
          geoId: "502075",
          destinationId: "1651828",
          landmarkCityDestinationId: "1506246",
          type: "LANDMARK",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.748445,
          longitude: -73.985668,
          searchDetail: null,
          caption:
            "Empire State Building, <span class='highlighted'>New</span> <span class='highlighted'>York</span>, New York, United States of America",
          name: "Empire State Building",
        },
      ],
    },
    {
      group: "TRANSPORT_GROUP",
      entities: [
        {
          geoId: "6185978",
          destinationId: "1730462",
          landmarkCityDestinationId: null,
          type: "TRAIN_STATION",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.75056,
          longitude: -73.994609,
          searchDetail: null,
          caption:
            "<span class='highlighted'>New</span> <span class='highlighted'>York</span> Penn Station, New York, New York, United States of America",
          name: "New York Penn Station",
        },
        {
          geoId: "4278092",
          destinationId: "1412655",
          landmarkCityDestinationId: null,
          type: "AIRPORT",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.77429,
          longitude: -73.872035,
          searchDetail: null,
          caption:
            "<span class='highlighted'>New</span> <span class='highlighted'>York</span>, NY, United States of America (LGA-LaGuardia)",
          name: "New York, NY (LGA-LaGuardia)",
        },
        {
          geoId: "4933194",
          destinationId: "1662393",
          landmarkCityDestinationId: null,
          type: "AIRPORT",
          redirectPage: "DEFAULT_PAGE",
          latitude: 40.644166,
          longitude: -73.782548,
          searchDetail: null,
          caption:
            "<span class='highlighted'>New</span> <span class='highlighted'>York</span>, NY, United States of America (JFK-John F. Kennedy Intl.)",
          name: "New York, NY (JFK-John F. Kennedy Intl.)",
        },
      ],
    },
  ],
  geocodeFallback: false,
};
